accounts/urls.py
from django.urls import path
from django.contrib.auth import  views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

collegecommunity/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('welcome/',views.WelcomePage.as_view(),name='welcome'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
]

posts/urls.py
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<pk>/",views.DeletePost.as_view(),name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>

    <meta charset="utf-8">
    <title>College Community</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@500&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static "collegecommunity/css/master.css" %}">
    <link rel="stylesheet" href="{% static "css/master.css" %}">



  </head>


  <body>
      <nav id="navbar">
        <div class="left">
          <a class="leftnav" href="{% url 'home' %}"><h1 style=font-size:50px>College Community</h1> </a>
        </div>

          <div class="right">

            <ul class="nav">
          						{% if user.is_authenticated %}
                        
                            <li><a href="{% url 'groups:all' %}"><h3>Groups</h3> </a></li>
                            <li><a href="{% url 'groups:create' %}"><h3>Create Group</h3> </a></li>
                            <li><a href="{% url 'accounts:logout' %}"><h3>Log Out</h3></a></li>

                      {% else %}

                          <li><a href="{% url 'accounts:login' %}"><h3>Log In</h3></a></li>
                          <li><a href="{% url 'accounts:signup' %}"><h3>Sign Up</h3> </a></li>
                        </ul>

                      {% endif %}
          </div>
      </nav>

              <div class="mycontent">

                {% block content %}

                {% endblock %}

            </div>

        <canvas id="canvas"></canvas>
  </body>
  <script src="{% static "collegecommunity/js/master.js" %}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
  <p style=font-size:50px>College Community helps you connect and share with the people of your interests.</p>
  {% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}

templates/welcome.html
{% extends "base.html" %}
{% block content %}
<div class="container">

<p style=font-size:50px>Welcome to College Community {{user.username}}!</p>



</div>

{% endblock %}